const express = require('express')
const pageController = require('../controllers/pageControllers')
const redirectMiddleware = require('../middlewares/redirectMiddleware')
const router = express.Router()
router.route('/').get(pageController.getIndexPage)
router.route('/about').get(pageController.getAboutPage)
router.route('/contact').get(pageController.getContactPage)
router.route('/contact').post(pageController.sendEmail)
router.route('/gallery').get(pageController.getGalleryPage)
router.route('/register').get(redirectMiddleware, pageController.getRegisterPage)
router.route('/login').get(redirectMiddleware, pageController.getLoginPage)
module.exports = router
